<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import { Save } from 'lucide-vue-next'
import { sellerApi } from '@/api/seller'
import { categoriesApi, brandsApi, type ApiBrand, type ApiCategory } from '@/api'
import { extractErrorMessage } from '@/api/errors'
const route = useRoute(); const router = useRouter(); const shopId = computed(() => Number(route.params.id)); const productId = computed(() => Number(route.params.productId)); const isEdit = computed(() => Boolean(productId.value)); const saving = ref(false); const loading = ref(false); const error = ref(''); const categories = ref<ApiCategory[]>([]); const brands = ref<ApiBrand[]>([])
const form = reactive({ name: '', sku: '', category_id: 0, brand_id: 0, short_description: '', description: '', price: 0, compare_at_price: null as number | null, weight: null as number | null, initial_stock: 0, is_active: true })
async function save() { saving.value = true; error.value = ''; try { const payload = { ...form, category_id: form.category_id || null, brand_id: form.brand_id || null, compare_at_price: form.compare_at_price || null, weight: form.weight || null }; if (isEdit.value) { delete (payload as Partial<typeof payload>).initial_stock; await sellerApi.updateProduct(shopId.value, productId.value, payload) } else await sellerApi.createProduct(shopId.value, payload); await router.push({ name: 'seller-shop-products', params: { id: shopId.value } }) } catch (cause) { error.value = extractErrorMessage(cause, 'Could not save the product.') } finally { saving.value = false } }
onMounted(async () => { loading.value = true; try { const [categoryResponse, brandResponse] = await Promise.all([categoriesApi.list(), brandsApi.list()]); categories.value = categoryResponse.data.data; brands.value = brandResponse.data.data; if (isEdit.value) { const product = (await sellerApi.getProduct(shopId.value, productId.value)).data.data; Object.assign(form, { name: product.name, sku: product.sku, category_id: product.category?.id ?? 0, brand_id: product.brand?.id ?? 0, short_description: product.short_description ?? '', description: product.description ?? '', price: product.price, compare_at_price: product.compare_at_price, weight: product.weight, is_active: product.is_active }) } } catch (cause) { error.value = extractErrorMessage(cause, 'Could not load product details.') } finally { loading.value = false } })
</script>
<template><form class="container-app mx-auto max-w-5xl space-y-5 py-10" @submit.prevent="save"><div class="flex flex-wrap items-end justify-between gap-4"><div><RouterLink :to="{ name: 'seller-shop-products', params: { id: shopId } }" class="text-xs font-semibold text-primary">Shop products</RouterLink><h1 class="mt-1 text-3xl font-bold text-ink">{{ isEdit ? 'Edit product' : 'Add product' }}</h1><p class="mt-1 text-sm text-gray-500">This product will belong to the selected shop only.</p></div><div class="flex gap-2"><RouterLink :to="{ name: 'seller-shop-products', params: { id: shopId } }" class="btn-secondary btn-sm">Cancel</RouterLink><button class="btn-primary btn-sm" :disabled="saving || loading"><Save class="h-4 w-4" />{{ saving ? 'Saving…' : 'Save product' }}</button></div></div><p v-if="error" class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ error }}</p><section class="card p-6"><div class="section-eyebrow">Product information</div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="sm:col-span-2"><span class="label">Product name *</span><input v-model="form.name" required class="input" /></label><label><span class="label">SKU</span><input v-model="form.sku" class="input" /></label><label><span class="label">Price *</span><input v-model.number="form.price" required min="0" step="0.01" type="number" class="input" /></label><label><span class="label">Category</span><select v-model.number="form.category_id" class="select"><option :value="0">No category</option><option v-for="category in categories" :key="category.id" :value="category.id">{{ category.name }}</option></select></label><label><span class="label">Brand</span><select v-model.number="form.brand_id" class="select"><option :value="0">No brand</option><option v-for="brand in brands" :key="brand.id" :value="brand.id">{{ brand.name }}</option></select></label><label class="sm:col-span-2"><span class="label">Short description</span><input v-model="form.short_description" class="input" maxlength="255" /></label><label class="sm:col-span-2"><span class="label">Description</span><textarea v-model="form.description" class="textarea" rows="6" /></label><label><span class="label">Compare-at price</span><input v-model.number="form.compare_at_price" min="0" step="0.01" type="number" class="input" /></label><label><span class="label">Weight</span><input v-model.number="form.weight" min="0" step="0.01" type="number" class="input" /></label><label v-if="!isEdit"><span class="label">Initial stock *</span><input v-model.number="form.initial_stock" required min="0" step="1" type="number" class="input" /><p class="mt-1 text-xs text-gray-500">You can adjust stock later from Inventory.</p></label><label class="sm:col-span-2 flex items-center gap-3"><input v-model="form.is_active" type="checkbox" class="h-4 w-4 accent-primary" /><span class="text-sm font-medium text-ink">Publish this product</span></label></div></section></form></template>
