<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import { Plus, Search, Store } from 'lucide-vue-next'
import { sellerApi } from '@/api/seller'
import type { AdminProduct } from '@/api/admin'
import { extractErrorMessage } from '@/api/errors'
import BasePagination from '@/components/BasePagination.vue'
import StatusTag from '@/components/StatusTag.vue'
import { formatPrice } from '@/utils/format'
const route = useRoute(); const shopId = computed(() => Number(route.params.id)); const products = ref<AdminProduct[]>([]); const page = ref(1); const pageCount = ref(1); const total = ref(0); const query = ref(''); const loading = ref(true); const error = ref(''); const deletingId = ref<number | null>(null)
async function load(target = page.value) { loading.value = true; error.value = ''; try { const { data } = await sellerApi.listProducts(shopId.value, { q: query.value || undefined, page: target }); products.value = data.data; page.value = data.meta.current_page; pageCount.value = data.meta.last_page; total.value = data.meta.total } catch (cause) { error.value = extractErrorMessage(cause, 'Could not load shop products.') } finally { loading.value = false } }
async function remove(product: AdminProduct) { if (!window.confirm(`Delete “${product.name}”? This product will no longer be sold.`)) return; deletingId.value = product.id; try { await sellerApi.deleteProduct(shopId.value, product.id); await load(products.value.length === 1 && page.value > 1 ? page.value - 1 : page.value) } catch (cause) { error.value = extractErrorMessage(cause, 'Could not delete the product.') } finally { deletingId.value = null } }
watch(shopId, () => load(1)); onMounted(load)
</script>
<template><div class="container-app mx-auto py-10"><header class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><RouterLink :to="{ name: 'seller-shop-dashboard', params: { id: shopId } }" class="text-xs font-semibold text-primary">Seller Center</RouterLink><h1 class="mt-1 text-3xl font-bold text-ink">Shop products</h1><p class="mt-1 text-sm text-gray-500">Only products belonging to this shop are visible here.</p></div><div class="flex gap-2"><div class="relative w-56"><Search class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input v-model="query" class="input h-9 w-full pl-9 text-sm" placeholder="Search products" @keyup.enter="load(1)" /></div><RouterLink :to="{ name: 'seller-shop-product-create', params: { id: shopId } }" class="btn-primary btn-sm"><Plus class="h-4 w-4" />Add product</RouterLink></div></header><div v-if="loading" class="card p-10 text-center text-sm text-gray-500">Loading products…</div><div v-else-if="error" class="card p-8 text-center text-red-600">{{ error }}</div><section v-else class="card overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-sm"><thead class="border-b border-border-gray bg-canvas/60 text-left text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Product</th><th class="px-4 py-3">SKU</th><th class="px-4 py-3 text-right">Price</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-border-gray"><tr v-if="!products.length"><td colspan="5" class="px-4 py-10 text-center text-gray-500"><Store class="mx-auto mb-2 h-7 w-7 text-gray-300" />No products in this shop.</td></tr><tr v-for="product in products" :key="product.id" class="hover:bg-canvas/50"><td class="px-4 py-3 font-semibold text-ink">{{ product.name }}</td><td class="px-4 py-3 text-xs text-gray-500">{{ product.sku }}</td><td class="px-4 py-3 text-right font-medium text-ink">{{ formatPrice(product.price) }}</td><td class="px-4 py-3"><StatusTag :status="product.is_active ? 'active' : 'inactive'" /></td><td class="px-4 py-3 text-right"><RouterLink :to="{ name: 'seller-shop-product-edit', params: { id: shopId, productId: product.id } }" class="btn-outline btn-sm !px-2.5 !py-1 text-xs">Edit</RouterLink><button class="ml-2 text-xs font-semibold text-red-600 hover:text-red-700 disabled:opacity-50" :disabled="deletingId === product.id" @click="remove(product)">{{ deletingId === product.id ? 'Deleting…' : 'Delete' }}</button></td></tr></tbody></table></div><div class="border-t border-border-gray p-4"><BasePagination :page="page" :page-count="pageCount" :page-size="15" :total-items="total" @update:page="load" /></div></section></div></template>
