<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import { Search, Warehouse } from 'lucide-vue-next'
import { sellerApi } from '@/api/seller'
import type { AdminInventoryItem } from '@/api/admin'
import { extractErrorMessage } from '@/api/errors'
import BasePagination from '@/components/BasePagination.vue'
import StatusTag from '@/components/StatusTag.vue'
const route = useRoute(); const shopId = computed(() => Number(route.params.id)); const inventory = ref<AdminInventoryItem[]>([]); const query = ref(''); const status = ref(''); const loading = ref(true); const error = ref(''); const page = ref(1); const pageCount = ref(1); const total = ref(0)
async function load(target = page.value) { loading.value = true; error.value = ''; try { const { data } = await sellerApi.listInventory(shopId.value, { q: query.value || undefined, stock_status: status.value || undefined, page: target }); inventory.value = data.data; page.value = data.meta.current_page; pageCount.value = data.meta.last_page; total.value = data.meta.total } catch (cause) { error.value = extractErrorMessage(cause, 'Could not load shop inventory.') } finally { loading.value = false } }
watch(shopId, () => load(1)); onMounted(load)
</script>
<template><div class="container-app mx-auto py-10"><header class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><RouterLink :to="{ name: 'seller-shop-dashboard', params: { id: shopId } }" class="text-xs font-semibold text-primary">Seller Center</RouterLink><h1 class="mt-1 text-3xl font-bold text-ink">Shop inventory</h1><p class="mt-1 text-sm text-gray-500">Stock records are limited to the selected shop.</p></div><div class="flex gap-2"><div class="relative w-56"><Search class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input v-model="query" class="input h-9 w-full pl-9 text-sm" placeholder="Search inventory" @keyup.enter="load(1)" /></div><select v-model="status" class="select h-9 text-sm" @change="load(1)"><option value="">All stock</option><option value="in">In stock</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></div></header><div v-if="loading" class="card p-10 text-center text-sm text-gray-500">Loading inventory…</div><div v-else-if="error" class="card p-8 text-center text-red-600">{{ error }}</div><section v-else class="card overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-sm"><thead class="border-b border-border-gray bg-canvas/60 text-left text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Product</th><th class="px-4 py-3">SKU</th><th class="px-4 py-3 text-right">Available</th><th class="px-4 py-3 text-right">Reserved</th><th class="px-4 py-3">Status</th></tr></thead><tbody class="divide-y divide-border-gray"><tr v-if="!inventory.length"><td colspan="5" class="px-4 py-10 text-center text-gray-500"><Warehouse class="mx-auto mb-2 h-7 w-7 text-gray-300" />No inventory records in this shop.</td></tr><tr v-for="item in inventory" :key="item.id" class="hover:bg-canvas/50"><td class="px-4 py-3 font-semibold text-ink">{{ item.product_name }}</td><td class="px-4 py-3 text-xs text-gray-500">{{ item.sku }}</td><td class="px-4 py-3 text-right font-medium text-ink">{{ item.available_quantity }}</td><td class="px-4 py-3 text-right text-gray-500">{{ item.reserved_quantity }}</td><td class="px-4 py-3"><StatusTag :status="item.is_out_of_stock ? 'out' : item.is_low_stock ? 'low' : 'active'" /></td></tr></tbody></table></div><div class="border-t border-border-gray p-4"><BasePagination :page="page" :page-count="pageCount" :page-size="15" :total-items="total" @update:page="load" /></div></section></div></template>
