<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Save, ShieldCheck, Store, UserRound } from 'lucide-vue-next'
import { adminApi, type AdminShop } from '@/api/admin'
import { extractErrorMessage } from '@/api/errors'

const props = defineProps<{ role: 'owner' | 'manager' }>()
const router = useRouter(); const shops = ref<AdminShop[]>([]); const saving = ref(false); const error = ref('')
const form = reactive({ name: '', email: '', phone: '', password: '', shop_id: 0, status: 'active' })
const isOwner = props.role === 'owner'; const label = isOwner ? 'Shop Owner' : 'Shop Admin'
async function save() { saving.value = true; error.value = ''; try { await adminApi.createShopMember({ ...form, role: props.role }); router.push({ name: isOwner ? 'admin-shop-owners' : 'admin-shop-admins' }) } catch (cause) { error.value = extractErrorMessage(cause, `Could not create ${label.toLowerCase()}.`) } finally { saving.value = false } }
onMounted(async () => { try { const { data } = await adminApi.listShops(); shops.value = data.data; form.shop_id = shops.value[0]?.id ?? 0 } catch (cause) { error.value = extractErrorMessage(cause, 'Could not load shops.') } })
</script>

<template>
  <form class="mx-auto max-w-[1400px] space-y-5 pb-16" @submit.prevent="save">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div class="mb-1 text-xs text-gray-400 dark:text-gray-500"><button type="button" class="hover:text-primary" @click="router.back()">{{ isOwner ? 'Shop Owners' : 'Shop Admins' }}</button><span class="mx-2">›</span>Create {{ label }}</div><h1 class="text-2xl font-bold tracking-tight text-ink">Create {{ label }}</h1><p class="mt-1 text-sm text-gray-500 dark:text-muted">Set up account access and assign this user to a marketplace shop.</p></div><div class="flex flex-wrap gap-2"><button class="btn-secondary btn-sm" type="button" @click="router.back()">Cancel</button><button class="btn-primary btn-sm" type="submit" :disabled="saving || !form.shop_id"><Save class="h-4 w-4" />{{ saving ? 'Saving...' : `Save ${label}` }}</button></div></div>
    <p v-if="error" class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ error }}</p>
    <section class="card p-6"><div class="section-eyebrow">Step 1</div><div class="mt-2 flex items-center gap-2"><UserRound class="h-5 w-5 text-primary" /><h2 class="text-lg font-semibold text-ink">Account Information</h2></div><p class="mt-1 text-sm text-gray-500 dark:text-muted">This information is used to sign in to the seller dashboard.</p><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="sm:col-span-2"><span class="label">Full name <span class="text-red-500">*</span></span><input v-model="form.name" required class="input" placeholder="Enter full name" /></label><label><span class="label">Email address <span class="text-red-500">*</span></span><input v-model="form.email" required type="email" class="input" placeholder="owner@example.com" /></label><label><span class="label">Phone number</span><input v-model="form.phone" class="input" placeholder="+855 10 123 456" /></label><label class="sm:col-span-2"><span class="label">Password <span class="text-red-500">*</span></span><input v-model="form.password" required minlength="8" type="password" class="input" placeholder="At least 8 characters" /><p class="mt-1 text-xs text-gray-500">The owner can change this password after signing in.</p></label></div></section>
    <section class="card p-6"><div class="section-eyebrow">Step 2</div><div class="mt-2 flex items-center gap-2"><Store class="h-5 w-5 text-primary" /><h2 class="text-lg font-semibold text-ink">Shop Assignment</h2></div><p class="mt-1 text-sm text-gray-500 dark:text-muted">Choose the shop this {{ label.toLowerCase() }} can manage.</p><div class="mt-5 grid gap-4 sm:grid-cols-2"><label><span class="label">Shop <span class="text-red-500">*</span></span><select v-model="form.shop_id" required class="select"><option :value="0" disabled>Select a shop</option><option v-for="shop in shops" :key="shop.id" :value="shop.id">{{ shop.name }}</option></select></label><label><span class="label">Account status <span class="text-red-500">*</span></span><select v-model="form.status" class="select"><option value="active">Active</option><option value="suspended">Suspended</option></select></label></div><div class="mt-5 flex items-start gap-3 rounded-xl bg-primary/5 p-4 text-sm text-gray-600 dark:text-muted"><ShieldCheck class="mt-0.5 h-5 w-5 shrink-0 text-primary" /><p>Active {{ label.toLowerCase() }} accounts can access the seller dashboard when their shop is approved.</p></div></section>
  </form>
</template>
