<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { CheckCircle2, Clock3, MoreHorizontal, Plus, Search, Store, Users, XCircle } from 'lucide-vue-next'
import { useRouter } from 'vue-router'
import { adminApi, type AdminShopMember } from '@/api/admin'
import { extractErrorMessage } from '@/api/errors'
import BasePagination from '@/components/BasePagination.vue'
import DataTableSkeleton from '@/components/DataTableSkeleton.vue'
import EmptyState from '@/components/EmptyState.vue'
import StatusTag from '@/components/StatusTag.vue'
import { formatDate } from '@/utils/format'
const props = defineProps<{ role: 'owner' | 'manager' }>(); const router = useRouter()
const members = ref<AdminShopMember[]>([]); const loading = ref(true); const error = ref(''); const query = ref(''); const status = ref(''); const page = ref(1); const pageCount = ref(1); const total = ref(0)
const counts = reactive({ all: 0, active: 0, suspended: 0, pending: 0 }); const title = computed(() => props.role === 'owner' ? 'Shop Owners' : 'Shop Admins')
const tabs = computed(() => [{ key: '', label: `All ${title.value}`, count: counts.all }, { key: 'pending', label: 'Pending', count: counts.pending }, { key: 'active', label: 'Active', count: counts.active }, { key: 'suspended', label: 'Suspended', count: counts.suspended }])
async function load(target = page.value) { loading.value = true; error.value = ''; try { const { data } = await adminApi.listShopMembers({ role: props.role, q: query.value || undefined, status: ['active', 'suspended'].includes(status.value) ? status.value : undefined, shop_status: status.value === 'pending' ? 'pending' : undefined, page: target }); members.value = data.data; page.value = data.meta.current_page; pageCount.value = data.meta.last_page; total.value = data.meta.total } catch (cause) { error.value = extractErrorMessage(cause, `Could not load ${title.value.toLowerCase()}.`) } finally { loading.value = false } }
async function loadCounts() { try { const [all, active, suspended, pending] = await Promise.all([adminApi.listShopMembers({ role: props.role }), adminApi.listShopMembers({ role: props.role, status: 'active' }), adminApi.listShopMembers({ role: props.role, status: 'suspended' }), adminApi.listShopMembers({ role: props.role, shop_status: 'pending' })]); Object.assign(counts, { all: all.data.meta.total, active: active.data.meta.total, suspended: suspended.data.meta.total, pending: pending.data.meta.total }) } catch {} }
function edit(member: AdminShopMember) { void router.push({ name: props.role === 'owner' ? 'admin-shop-owner-edit' : 'admin-shop-admin-edit', params: { id: member.id } }) }
watch(() => props.role, () => { status.value = ''; void Promise.all([load(1), loadCounts()]) }); onMounted(() => void Promise.all([load(), loadCounts()]))
</script>
<template>
  <div class="mx-auto max-w-[1600px] space-y-4 sm:space-y-5"><section class="flex items-end justify-between gap-4"><div><h1 class="text-2xl font-bold tracking-tight text-ink">{{ title }}</h1><p class="mt-1 text-sm text-gray-500 dark:text-muted">Manage {{ title.toLowerCase() }}, their shops, and account status.</p></div><button class="btn-primary !px-4 !py-2" @click="router.push({ name: props.role === 'owner' ? 'admin-shop-owner-create' : 'admin-shop-admin-create' })"><Plus class="h-4 w-4" />Add {{ props.role === 'owner' ? 'Shop Owner' : 'Shop Admin' }}</button></section>
    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article v-for="card in [{ label: `Total ${title}`, value: counts.all, icon: Users, tone: 'bg-blue-50 text-blue-600' }, { label: 'Pending Approval', value: counts.pending, icon: Clock3, tone: 'bg-amber-50 text-amber-600' }, { label: 'Active', value: counts.active, icon: CheckCircle2, tone: 'bg-emerald-50 text-emerald-600' }, { label: 'Suspended', value: counts.suspended, icon: XCircle, tone: 'bg-red-50 text-red-500' }]" :key="card.label" class="card p-4"><div class="flex gap-3"><div class="flex h-11 w-11 items-center justify-center rounded-xl" :class="card.tone"><component :is="card.icon" class="h-5 w-5" /></div><div><p class="text-xs text-gray-500">{{ card.label }}</p><p class="mt-1 text-xl font-bold text-ink">{{ card.value }}</p></div></div></article></section>
    <section class="flex flex-wrap items-center justify-between gap-3"><div class="flex gap-1"><button v-for="tab in tabs" :key="tab.key" class="rounded-lg px-3 py-2 text-xs font-semibold" :class="status === tab.key ? 'bg-primary text-white' : 'text-gray-500 hover:bg-surface-hover'" @click="status = tab.key; load(1)">{{ tab.label }} <span class="ml-1 rounded-full px-1.5 py-0.5" :class="status === tab.key ? 'bg-white/20' : 'bg-gray-100'">{{ tab.count }}</span></button></div><div class="relative w-full sm:w-60"><Search class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input v-model="query" class="input h-9 w-full pl-9 text-xs" :placeholder="`Search ${title.toLowerCase()}...`" @keyup.enter="load(1)" /></div></section>
    <DataTableSkeleton v-if="loading" :rows="7" :columns="7" /><div v-else-if="error" class="card p-8 text-center text-red-600">{{ error }}</div><section v-else-if="members.length" class="card overflow-visible"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-sm"><thead class="border-b border-border-gray bg-canvas/60 text-left text-[11px] uppercase text-gray-500"><tr><th class="px-4 py-3">#</th><th class="px-4 py-3">Owner</th><th class="px-4 py-3">Shop</th><th class="px-4 py-3">Contact</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Joined at</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-border-gray"><tr v-for="(member, index) in members" :key="member.id" class="hover:bg-canvas/50"><td class="px-4 py-3">{{ (page - 1) * 20 + index + 1 }}</td><td class="px-4 py-3"><p class="font-semibold text-ink">{{ member.user.name }}</p><p class="text-xs text-gray-500">{{ member.user.email }}</p></td><td class="px-4 py-3"><div class="flex items-center gap-2"><Store class="h-4 w-4 text-primary" /><span class="font-medium text-ink">{{ member.shop.name }}</span></div></td><td class="px-4 py-3 text-xs">{{ member.user.phone || '—' }}</td><td class="px-4 py-3"><StatusTag :status="member.status" /></td><td class="px-4 py-3 text-xs text-gray-500">{{ formatDate(member.joined_at) }}</td><td class="px-4 py-3 text-right"><details class="relative inline-block"><summary class="btn-icon h-7 w-7 list-none cursor-pointer" title="More actions"><MoreHorizontal class="h-4 w-4" /></summary><div class="absolute right-0 top-8 z-20 w-28 overflow-hidden rounded-lg border border-border-gray bg-surface py-1 text-left shadow-popover"><button class="block w-full px-3 py-2 text-left text-xs font-medium text-ink hover:bg-canvas" @click="edit(member)">Edit</button></div></details></td></tr></tbody></table></div><div class="border-t border-border-gray p-4"><BasePagination :page="page" :page-count="pageCount" :total-items="total" :page-size="20" @update:page="load" /></div></section><EmptyState v-else :title="`No ${title.toLowerCase()} found`" description="Try changing your search or status filter."><template #icon><Users class="h-10 w-10 text-gray-300" /></template></EmptyState></div>
</template>
